apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-child       
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dzoro17/argocd-demos.git
    targetRevision: main
    path: app_of_apps/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
